/* Generated By:JavaCC: Do not edit this line. SyntaxAnalyser.java */
import java.io.*;
import java.io.FileWriter;
import java.nio.charset.*;
import net.sourceforge.plantuml.*;
import java.awt.image.*;
import javax.imageio.*;
import java.util.*;
import java.lang.*;

public class SyntaxAnalyser implements SyntaxAnalyserConstants {
        public static void main(String args[])throws ParseException , IOException
        {
          String line = null;
          int i=0;
          String ClassName = "";
          FileInputStream fis = null;
          File file =new File("JavaInput.java");
          File outputFile = new File("umlInput.txt");
          FileWriter fw = new FileWriter(outputFile.getAbsoluteFile());
          BufferedWriter bw = new BufferedWriter(fw);
          String UmlData ="";
                try
                {

                        UmlData +="@startuml"+'\u005cn';
            SyntaxAnalyser analyser = new SyntaxAnalyser(new FileInputStream(file));
            while(true)
            {
                ClassName = analyser.GetId();
                if(ClassName != "0")
                {
                                        UmlData+= ClassName+'\u005cn';
                                        System.out.println(UmlData);
                                }
                else
                {
                        System.out.println("else");
                                        String EndUml = "@enduml";
                                        UmlData += EndUml;
                                        bw.write(UmlData);
                                        bw.close();
                                        break;
                    }

                        }

                        ByteArrayOutputStream output = new ByteArrayOutputStream();
                        UmlData = "";
                        BufferedReader br = new BufferedReader(new FileReader(outputFile));
                        while ((line = br.readLine()) != null) {
                        UmlData+=line+'\u005cn';
                }
                System.out.println(UmlData);
                        SourceStringReader reader=new SourceStringReader(UmlData);
                        String desc =reader.generateImage(output);
                        byte [] data = output.toByteArray();
                        InputStream inputImageStream = new ByteArrayInputStream(data);
                        BufferedImage umlImage = ImageIO.read(inputImageStream);
                        ImageIO.write(umlImage, "png", new java.io.File("D:\u005c\u005cimage.png"));

                        System.out.print(desc);

                }catch(FileNotFoundException ex){
                        System.out.println("FIle not found");
                }catch(IOException ex)
                {
                  System.out.println("FIle not found1");
                }

}

  final public String GetId() throws ParseException {
        String className;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PUBLIC:
      className = keyword();
    {if (true) return className;}
      break;
    case 0:
      jj_consume_token(0);
    {if (true) return "0";}
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String keyword() throws ParseException {
         String output;
         String id = "";
         Token idName=null;
         Token InheritedClass = null;
         Token ImplementedClass = null;
         String[] interfaceList=new String[9999];
         //String Name = null;
         boolean i = false;
    jj_consume_token(PUBLIC);
    jj_consume_token(CLASS);
    idName = jj_consume_token(ID);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EXTENDS:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      jj_consume_token(EXTENDS);
      InheritedClass = jj_consume_token(ID);
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IMPLEMENTS:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      jj_consume_token(IMPLEMENTS);
      ImplementedClass = jj_consume_token(ID);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case DELIMITER:
          ;
          break;
        default:
          jj_la1[3] = jj_gen;
          break label_3;
        }
        jj_consume_token(DELIMITER);
        jj_consume_token(ID);
      }
    }
          if(ImplementedClass.toString().contains(","))
          {
            interfaceList = ImplementedClass.toString().split(",");

          }
          else
          {
            interfaceList[0]=  ImplementedClass.toString();
          }
      if(InheritedClass != null && interfaceList.length==0)
      {

      id = "class" + InheritedClass.toString()+ "<|--" +"class" + " " + idName.toString();
      {if (true) return id;}
          }
          else if(interfaceList.length !=0 && InheritedClass==null )
          {
            for (int j=0;j<interfaceList.length;j++)
            {

            id = interfaceList[j] + "()-"+"class"+idName.toString();
            {if (true) return id;}
            }
          }
          else if(ImplementedClass !=null && InheritedClass != null)
          {
            id = "class" + InheritedClass.toString()+ "<|--" +"class" + " " + idName.toString()+"\u005cn";
            for (int j=0;j<interfaceList.length;j++)
            {
              id+= interfaceList[j]+" "+"()-"+" "+idName.toString();
              {if (true) return id;}
            }

          }
        else
        {
           id =  "class" + " " + idName.toString();
            {if (true) return id;}
         }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public SyntaxAnalyserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[4];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x21,0x100,0x1000,0x2000,};
   }

  /** Constructor with InputStream. */
  public SyntaxAnalyser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SyntaxAnalyser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SyntaxAnalyserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public SyntaxAnalyser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SyntaxAnalyserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public SyntaxAnalyser(SyntaxAnalyserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(SyntaxAnalyserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[14];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 4; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 14; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
