/* Generated By:JavaCC: Do not edit this line. SyntaxAnalyserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxAnalyserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PUBLIC = 5;
  /** RegularExpression Id. */
  int STATIC = 6;
  /** RegularExpression Id. */
  int EXTENDS = 7;
  /** RegularExpression Id. */
  int IMPLEMENTS = 8;
  /** RegularExpression Id. */
  int DELIMITER = 9;
  /** RegularExpression Id. */
  int OP = 10;
  /** RegularExpression Id. */
  int IMPORT = 11;
  /** RegularExpression Id. */
  int SEMICOLON = 12;
  /** RegularExpression Id. */
  int DATATYPE = 13;
  /** RegularExpression Id. */
  int CLOSINGBRACKET = 14;
  /** RegularExpression Id. */
  int OPENINGBRACKET = 15;
  /** RegularExpression Id. */
  int TYPE = 16;
  /** RegularExpression Id. */
  int ID = 17;
  /** RegularExpression Id. */
  int PACKAGES = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"public\"",
    "\"static\"",
    "\"extends\"",
    "\"implements\"",
    "\",\"",
    "<OP>",
    "\"import\"",
    "\";\"",
    "<DATATYPE>",
    "\")\"",
    "\"(\"",
    "<TYPE>",
    "<ID>",
    "<PACKAGES>",
  };

}
