/* Generated By:JavaCC: Do not edit this line. SyntaxAnalyser.java */
import java.io.*;
import java.io.FileWriter;
import java.nio.charset.*;
import net.sourceforge.plantuml.*;
import java.awt.image.*;
import javax.imageio.*;
import java.util.*;
import java.lang.*;

public class SyntaxAnalyser implements SyntaxAnalyserConstants {
        public static void main(String args[])throws ParseException , IOException
        {
          String line = null;
          int i=0;
          String ClassName = "";
          FileInputStream fis = null;
          File file =new File("JavaInput.java");
          File outputFile = new File("umlInput.txt");
          FileWriter fw = new FileWriter(outputFile.getAbsoluteFile());
          BufferedWriter bw = new BufferedWriter(fw);
          String UmlData ="";
                try
                {

                        UmlData +="@startuml"+'\u005cn';
            SyntaxAnalyser analyser = new SyntaxAnalyser(new FileInputStream(file));
            while(true)
            {
                ClassName = analyser.GetId();
                if(ClassName != "0")
                {
                                        UmlData+= ClassName+'\u005cn';
                                        System.out.println(UmlData);
                                }
                else
                {
                        System.out.println("else");
                                        String EndUml = "@enduml";
                                        UmlData += EndUml;
                                        bw.write(UmlData);
                                        bw.close();
                                        break;
                    }

                        }

                        ByteArrayOutputStream output = new ByteArrayOutputStream();
                        UmlData = "";
                        BufferedReader br = new BufferedReader(new FileReader(outputFile));
                        while ((line = br.readLine()) != null) {
                        UmlData+=line+'\u005cn';
                }
                System.out.println(UmlData);
                        SourceStringReader reader=new SourceStringReader(UmlData);
                        String desc =reader.generateImage(output);
                        byte [] data = output.toByteArray();
                        InputStream inputImageStream = new ByteArrayInputStream(data);
                        BufferedImage umlImage = ImageIO.read(inputImageStream);
                        ImageIO.write(umlImage, "png", new java.io.File("D:\u005c\u005cimage.png"));

                        System.out.print(desc);

                }catch(FileNotFoundException ex){
                        System.out.println("FIle not found");
                }catch(IOException ex)
                {
                  System.out.println("File not found1");
                }

}

  final public String GetId() throws ParseException {
        String className;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PUBLIC:
    case IMPORT:
      className = keyword();
    {if (true) return className;}
      break;
    case 0:
      jj_consume_token(0);
    {if (true) return "0";}
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String keyword() throws ParseException {
         String output;
         String id = "";
         Token idName=null;
         Token InheritedClass = null;
         Token ImplementedClass = null;
         ArrayList list1 = new ArrayList();
         HashMap<String, String> VarNames = new HashMap<String, String>();
         HashMap<String, String> MethodNames = new HashMap<String, String>();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IMPORT:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      jj_consume_token(IMPORT);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ID:
      case PACKAGES:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PACKAGES:
          jj_consume_token(PACKAGES);
          break;
        case ID:
          jj_consume_token(ID);
          break;
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      jj_consume_token(SEMICOLON);
    }
    jj_consume_token(PUBLIC);
    jj_consume_token(CLASS);
    idName = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EXTENDS:
      jj_consume_token(EXTENDS);
      InheritedClass = jj_consume_token(ID);
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IMPLEMENTS:
      jj_consume_token(IMPLEMENTS);
      ImplementedClass = jj_consume_token(ID);
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    list1 = AllInterFaces();
    jj_consume_token(OP);
    VarNames = GetVariableNames();
    jj_consume_token(OP);
          id =  "class" + " " + idName.toString()+"\u005cn";
      if(InheritedClass != null)
      {
        id+= "class" + InheritedClass.toString()+ "<|--" +"class" + " " + idName.toString()+"\u005cn";
      }
          if(ImplementedClass !=null)
          {
            id += ImplementedClass.toString() + "()-"+idName.toString()+"\u005cn";
          }
          if(list1!=null)
          {
            for(int i=0;i<list1.size();i++)
            {
              id+= list1.get(i).toString()+" "+"()-"+" "+idName.toString()+"\u005cn";

                }
          }
          id+="class"+ " " + idName.toString()+"{";
          Set setVariable = VarNames.entrySet();
          Set setMethod = MethodNames.entrySet();
          Iterator iterator1 = setVariable.iterator();
          Iterator iterator2 = setMethod.iterator();
           while(iterator1.hasNext()) {
          Map.Entry mentry = (Map.Entry)iterator1.next();
          id+="\u005cn\u005ct"+mentry.getKey()+" : "+mentry.getValue();
      }
      id+="\u005cn}";
      /*
      while(iterator2.hasNext()) {
          Map.Entry mentry = (Map.Entry)iterator2.next();
          id+="\n\t"+mentry.getKey()+"()"+" : "+mentry.getValue();
      }
      id+="\n}";*/
          {if (true) return id;}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList AllInterFaces() throws ParseException {
   String AllInterface = new String();
   Token idName=null;
   ArrayList identifier = new ArrayList();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DELIMITER:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_2;
      }
      jj_consume_token(DELIMITER);
      idName = jj_consume_token(ID);
    }
            if(idName != null)
            {
              identifier.add(idName.toString());
                  {if (true) return identifier;}
                }
                else
                        {if (true) return null;}
    throw new Error("Missing return statement in function");
  }

  final public HashMap GetVariableNames() throws ParseException {
  Token VarName=null;
  Token Dtype=null;
  HashMap<String, String> hm = new HashMap<String, String>();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUBLIC:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      jj_consume_token(PUBLIC);
      Dtype = jj_consume_token(DATATYPE);
      VarName = jj_consume_token(ID);
      jj_consume_token(SEMICOLON);
     hm.put(VarName.toString(),Dtype.toString());
    }
    {if (true) return hm;}
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public SyntaxAnalyserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[8];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x2021,0x2000,0x40200,0x40200,0x100,0x400,0x800,0x20,};
   }

  /** Constructor with InputStream. */
  public SyntaxAnalyser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SyntaxAnalyser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SyntaxAnalyserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public SyntaxAnalyser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SyntaxAnalyserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public SyntaxAnalyser(SyntaxAnalyserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(SyntaxAnalyserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[19];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 8; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 19; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
